# Generated by Django 3.2.15 on 2022-10-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20221002_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
