# Generated by Django 3.2.15 on 2022-10-17 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_cocktail_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remark',
            name='approved',
        ),
    ]
