# Generated by Django 3.2.15 on 2022-12-07 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20221111_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='status',
        ),
    ]
